backend:
  name: github
  repo: dannyhope/uxbrighton # Path to the GitHub code repository
  branch: gh-pages # Branch that Netlify CMS will be available on
  site_domain: uxbri-netlify-cms.netlify.com # Using a placeholder Netlify site and custom Netlify domain to enable the backend OAuth configuration

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']

# These lines should *not* be indented
publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with images/uploads
site_url: https://uxbri.org/
display_url: https://uxbri.org/
logo_url: https://uxbri.org/2022/logo/red-square-small.png

collections:
  - label: "Conferences"
    name: "conferences"
    files:
      - label: "UX Brighton 2022"
        name: "uxbri-2022"
        file: "2022/index.html"
        fields:
          - {label: "Title", name: "title", hint: "Primary title of the page.", widget: "string"}
          - {label: "Description", name: "description", hint: "This is *meta* content. Beneficial to SEO.", widget: "string"}
          - {label: "Page URL", name: "fullurl", hint: "This is *meta* content. Social channels & SEO.", widget: "string", default: "https://uxbri.org/2022/"}
          - {label: "Slug", name: "slug", widget: "string", default: "conference-2022"}
          - label: "Hero" # Hero section
            name: "hero"
            summary: "Hero section content - (eg. hero image & ticket button)."
            widget: "object"
            collapsed: true
            fields:
              - {label: "Hero Background Image", name: "hero-image", widget: "string", default: "/2022/images/header.jpg"}
              - label: "Button"
                name: "button"
                summary: "Ticket button."
                widget: "object"
                collapsed: true
                fields:
                  - {label: "Button visibility", name: "ticket-button", hint: "Choose whether to *show* or *hide* the ticket button. Defaults to *show*.", widget: "select", options: ["show", "hide"], default: ["show"]}
                  - {label: "Button text", name: "ticket-button-text", hint: "Text in the button.", widget: "string"}
                  - {label: "Button text - extra", name: "ticket-button-extra-text", hint: "This text appears just below the button.", widget: "string", required: false}
                  - {label: "Button URL Address", name: "ticket-button-url", hint: "URL this button points to.", widget: "string"}
          - label: "Event Promotions" # Event Promotions
            name: "events"
            summary: "Event promotion content - (top & bottom of page)."
            widget: "object"
            collapsed: true
            fields:
              - {label: "Event Promotion (top)", name: "event-promo-top-of-page", hint: "Event promotion showing at top of page. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Event Promotion (footer)", name: "event-promo-footer", hint: "Event promotion showing at the bottom of the page. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
          - label: "Pre & During Conference" # Pre & During Conference
            name: "pre-and-during-conf"
            summary: "Pre & during conference content - (eg. pre-party, speakers & workshops)."
            widget: "object"
            collapsed: true
            fields:
              - {label: "Travel & Accommodation", name: "travel-and-accommodation-blurb", hint: "Travel & accommodation info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Pre party", name: "pre-party", hint: "Pre party info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Speakers", name: "speakers", hint: "Speakers info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Sponsors", name: "sponsors", hint: "Sponsors info. Choose whether to *show* or *hide*. Defaults to *show*.", widget: "select", options: ["show", "hide"], default: ["show"]}
              - {label: "Highlights", name: "highlights", hint: "Highlights info. Choose whether to *show* or *hide*. Defaults to *show*.", widget: "select", options: ["show", "hide"], default: ["show"]}
              - {label: "Workshops", name: "workshops", hint: "Workshops info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
          - label: "Speakers, Talks & Schedule" # Speakers, Talks & Schedule
            name: "speakers-and-schedule"
            summary: "Speakers, Talks & Schedule content - (eg. registration times, talk times & after party)."
            widget: "object"
            collapsed: true
            fields:
              - {label: "Talk times", name: "talk-times", hint: "Talk times info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Registration", name: "registration", hint: "Registration info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "After party", name: "after-party", hint: "After party info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
          - label: "Post Conference" # Post Conference
            name: "post-conf"
            summary: "Post conference content - (eg. talk slides & talk videos)."
            widget: "object"
            collapsed: true
            fields:
              - {label: "Talk slides", name: "talk-slides", hint: "Talk slides info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}
              - {label: "Talk videos", name: "talk-videos", hint: "Talk videos info. Choose whether to *show* or *hide*. Defaults to *hide*.", widget: "select", options: ["show", "hide"], default: ["hide"]}